name: TameOfThrones Build and Test

on: [push]

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 3.0.100
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - name: Build with dotnet
      run: dotnet build ./TameOfThrones/src/Set5.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./TameOfThrones/src/Set5.sln --configuration Release
